services:
  server:
    build: .
    container_name: tfd-api-server
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - .env:/app/.env
      - ./upload:/app/upload
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: tfd-api-nginx
    depends_on:
      - server
    environment:
      - NGINX_SERVER_NAME=localhost
      - NEST_HOST=server
      - NEST_PORT=3000
      - NGINX_MAX_BODY=100M
    ports:
      - '80:80'
  db:
    image: postgres:14.10
    container_name: tfd-api-db
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
    ports:
      - '5432:5432'
    volumes:
      - postgresdata:/var/lib/postgresql
  redis:
    image: redis:5
    container_name: tfd-api-redis
    ports:
      - '6379:6379'
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:tfd-api-redis:6379
    ports:
      - "8082:8081"
    depends_on:
      - redis
  smtp:
    image: mailhog/mailhog
    container_name: smtp
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
volumes:
  postgresdata:
